language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - graphviz

before_script:
  - pip3 install git+https://github.com/antmicro/tuttest

script:
  - tuttest README.md doc-build | bash -
